### ISSUE TITLE
potential issue in multi-thread mode

### ISSUE THREAD

**Issue by zimmermann6** [fplll/fplll#479]
I have an issue when I use lll_reduction within the bacsel tool (https://gitlab.inria.fr/zimmerma/bacsel) in multi-thread mode. The issue disappears with only one thread, or when I use LM_PROVED instead of LM_WRAPPER, which makes me think it is related to fplll. To reproduce, use revision b7f6b0d of bacsel:
```
make GMP=... MPFR=... DEFSAL="-DACOS -DBASIS=2 -DAUTOMATIC"
./bacsel -rnd_mode all -prec 128 -n 53 -nn 53 -m 43 -t 19.6 -t0 4503599627370496 -t1 9007199254740992 -d 2 -alpha 2 -v -e_in -9 -nthreads 64
...
Dimensions of the lattices: 6x9
../../src/get_ld.c:333: MPFR assertion failed: (ret >= 0.5 && ret < 1.0) || (ret <= -0.5 && ret > -1.0)
```
gdb says:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6ba5537 in __GI_abort () at abort.c:79
#2  0x00007ffff6bfe768 in __libc_message (action=action@entry=do_abort,
    fmt=fmt@entry=0x7ffff6d0ce2d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff6c05a5a in malloc_printerr (
    str=str@entry=0x7ffff6d0f1c8 "double free or corruption (fasttop)")
    at malloc.c:5347
#4  0x00007ffff6c06d55 in _int_free (av=0x7ffec4000020, p=0x7ffec4001cc0,
    have_lock=0) at malloc.c:4266
#5  0x00007ffff714e299 in mpfr_free_func ()
   from /lib/x86_64-linux-gnu/libmpfr.so.6
#6  0x00007ffff7145f0d in mpfr_clear () from /lib/x86_64-linux-gnu/libmpfr.so.6
#7  0x00007ffff77face0 in int fplll::Wrapper::call_lll<__mpz_struct [1], double>(fplll::ZZ_mat<__mpz_struct [1]>&, fplll::ZZ_mat<__mpz_struct [1]>&, fplll::ZZ_mat<__mpz_struct [1]>&, fplll::LLLMethod, int, double, double) ()
   from /lib/x86_64-linux-gnu/libfplll.so.7
#8  0x00007ffff77e6197 in fplll::Wrapper::lll() ()
   from /lib/x86_64-linux-gnu/libfplll.so.7
#9  0x00007ffff77e62fb in int fplll::lll_reduction_wrapper<__mpz_struct [1]>(fplll::ZZ_mat<__mpz_struct [1]>&, fplll::ZZ_mat<__mpz_struct [1]>&, fplll::ZZ_mat<__mpz_struct [1]>&, double, double, fplll::FloatType, int, int) ()
   from /lib/x86_64-linux-gnu/libfplll.so.7
#10 0x00007ffff77e64bb in fplll::lll_reduction(fplll::ZZ_mat<__mpz_struct [1]>&, double, double, fplll::LLLMethod, fplll::FloatType, int, int) ()
   from /lib/x86_64-linux-gnu/libfplll.so.7
#11 0x000055555555e258 in LLLReduce (B=B@entry=0x7fff74001680, d=d@entry=6,
    n=n@entry=9, precision=<optimized out>) at fplll_wrapper.cpp:165
#12 0x000055555555bba2 in slz (Res=Res@entry=0x7ffff4b48630,
    Nb=Nb@entry=0x7ffff4b4862c, P=P@entry=0x7fff740010a0,
    C=C@entry=0x7ffff4b48650, T=T@entry=0x7ffff4b48680, d=d@entry=2, alpha=2,
    tmp=0x7ffff4b48740, W=0x7ffff4b48710, npols=6, ncoefs=9,
    ztmp=<optimized out>, Calpha=0x7ffff4b486c0, ztmp2=0x7ffff4b486b0,
    ok=0x7fff74000f90, PP=0x7fff74000fc0, Ptmp=0x7fff74001000,
    B_lll=0x7fff74001680, time_4_lll=0x7ffff4b48638,
    time_4_Hensel=0x7ffff4b48640, Sol=0x7ffff4b48720, h=0x7ffff4b488c0)
    at slz.c:407
```

**Comment by zimmermann6** [comment]
I should add the issue is not deterministic: sometimes the program runs smoothly, sometimes we get simply a "Segmentation fault".

**Comment by zimmermann6** [comment]
while looking at the fplll code, a potential reason is the following: in ```nr_Z.inl```, the function ```init_temp()``` initializes (I believe) a static variable, which is shared by all threads. There should be one variable per thread.

**Comment by joerowell** [comment]
I'll attempt to fix this some time this afternoon.

**Comment by zimmermann6** [comment]
thank you Joe, I will try your fix. Strangely, I did not get any email when you did push the new branch.

**Comment by zimmermann6** [comment]
I confirm the problem is fixed with my example. Thank you very much for the quick fix!
